const songs = [
    //KANTO
    { label: "Blue", answers: ["blue", "champion blue", "kanto rival", "kanto champion"], fullName: ["Final Battle! Rival - Red/Green/Yellow", "Champion Battle! - FireRed/LeafGreen"], type: "person", region: "Kanto",
    fileUrl: ["https://vgmsite.com/soundtracks/pokemon-red-green-blue-yellow/pvfhbfvjzj/51%20Final%20Battle%21%20%28Rival%29.mp3", "https://vgmsite.com/soundtracks/pokemon-firered-leafgreen-enhanced-soundtrack/brucswgjao/63%20Champion%20Battle%21.mp3"], 
    imgUrl: ["https://docs.google.com/uc?export=download&id=16hiJMig3xQKuY2_ikneF0yBrWLO5vlfp"] },
    { label: "Giovanni", answers: ["giovanni", "team rocket boss giovanni"], fullName: ["Battle! (Team Rocket Boss Giovanni) - Ultra Sun/Ultra Moon"], type: "person", region: "Kanto",
    fileUrl: ["https://vgmsite.com/soundtracks/pokemon-ultra-sun-and-pokemon-ultra-moon-battle-music-selection/stwokozcnh/13.%20Battle%21%20%28Team%20Rocket%20Boss%20Giovanni%29.mp3"], 
    imgUrl: ["https://docs.google.com/uc?export=download&id=1IMvnq0KU3-Z1C_ROc9xTvdYw51PHjm-H"] },
    { label: "Red/Blue", answers: ["red", "blue", "red and blue", "blue and red"], fullName: ["Battle! (Champion Red & Blue) - Ultra Sun/Ultra Moon"], type: "person", region: "Kanto/Alola",
    fileUrl: ["https://vgmsite.com/soundtracks/pokemon-ultra-sun-and-pokemon-ultra-moon-battle-music-selection/vbddhotrin/16.%20Battle%21%20%28Champion%20Red%20%26%20Blue%29.mp3"], 
    imgUrl: ["https://docs.google.com/uc?export=download&id=1IIfrA8chW54PyzV0otIDpIfiqQvtboA6","https://docs.google.com/uc?export=download&id=1Kl08MJveTbwunrhJxEW01_xOcDHYQkEC"] },
    { label: "Kanto Gym", answers: ["kanto gym"], fullName: ["Gym Leader Battle - Red/Green/Yellow", "Battle! (Gym Leader Battle) - FireRed/LeafGreen"], type: "event", region: "Kanto",
    fileUrl: ["https://vgmsite.com/soundtracks/pokemon-red-green-blue-yellow/ppdgehuibt/28%20Battle%21%20%28Gym%20Leader%20Battle%29.mp3", "https://vgmsite.com/soundtracks/pokemon-firered-leafgreen-enhanced-soundtrack/ejruzgslql/27%20Gym%20Leader%20Battle%21.mp3"], 
    imgUrl: ["https://docs.google.com/uc?export=download&id=19ckuFHW887Hh96dgAjZXUIqMlxfcDSFu", "https://docs.google.com/uc?export=download&id=1_AboVeta75GVEWVmZoNtZz1pW9GyKJen", "https://docs.google.com/uc?export=download&id=1jG8-b782S3ywKgrhUpOJiZPkKSj_3w6D", "https://docs.google.com/uc?export=download&id=1TGOSBfNaIrPysdYnaFQXhnNNJqQrMukw", "https://docs.google.com/uc?export=download&id=1j45wRKfmEfogZf8b2v6gouZhLOHprQhL", "https://docs.google.com/uc?export=download&id=1FQVIYqta1eC_urA-iLWoMt3rEE4llV__", "https://docs.google.com/uc?export=download&id=1qcHgqn3wYdFrvnH17Fm_cSt7UOKdQEBF", "https://docs.google.com/uc?export=download&id=1x6lCHpL4aV1yeYbv9M3tNMVk4T-GM9Sn"] },
    { label: "Mewtwo", answers: ["mewtwo"], fullName: ["Mewtwo Battle! - FireRed/LeafGreen", "Battle! (Mewtwo) - Ultra Sun/Ultra Moon"], type: "pokemon", region: "Kanto",
    fileUrl: ["https://vgmsite.com/soundtracks/pokemon-firered-leafgreen-enhanced-soundtrack/fdhjgvmiss/69%20Mewtwo%20Battle%21.mp3","https://vgmsite.com/soundtracks/pokemon-ultra-sun-and-pokemon-ultra-moon-battle-music-selection/ightayfdft/17.%20Battle%21%20%28Mewtwo%29.mp3"], 
    imgUrl: ["https://docs.google.com/uc?export=download&id=170MsIJpeLFjyv-e-x1iCPUMrCmowwbB4", "https://docs.google.com/uc?export=download&id=1xUpYckt7BqH4RivAQ0kxPl9FXImInfob", "https://docs.google.com/uc?export=download&id=15N1zCL4nLfm35bidhZYWm3oaJiPCDuOQ"] },
    //4
    //JOHTO 
    { label: "Lance/Red", answers: ["lance", "champion lance", "red", "johto champion"], fullName: ["Battle! (Champion) - Gold/Silver/Crystal (theme is shared with Red)", "Battle! (Champion) - HeartGold/SoulSilver (theme is shared with Red)"], type: "person", region: "Johto",
    fileUrl: ["https://vgmsite.com/soundtracks/pokemon-gold-silver-crystal/sgjalmzw/120%20Battle%21%20Champion.mp3","https://vgmsite.com/soundtracks/pokemon-heartgold-and-soulsilver-music-super-complete/vkvdahkuiq/2-78%20Battle%21%20Champion.mp3"], 
    imgUrl: ["https://docs.google.com/uc?export=download&id=19_c1Y3t3-1r9N_qdjOppvYgLEFlI_46M", "https://docs.google.com/uc?export=download&id=1CHZ45yfWDtmC_o7DrdI1ltTCR5LZbAR1"] },
    { label: "Silver", answers: ["silver", "johto rival"], fullName: ["Battle! (Rival) - Gold/Silver/Crystal", "Battle! (Rival) - HeartGold/SoulSilver"], type: "person", region: "Johto",
    fileUrl: ["https://vgmsite.com/soundtracks/pokemon-gold-silver-crystal/ycqgzdbw/036%20Battle%21%20Rival.mp3", "https://vgmsite.com/soundtracks/pokemon-heartgold-and-soulsilver-music-super-complete/bgluyxedcz/1-38%20Battle%21%20Rival.mp3"], 
    imgUrl: ["https://docs.google.com/uc?export=download&id=10jMC5No8wy6HezMue1rNmiI5oaSxseDo"] },
    { label: "Johto Gym", answers: ["johto gym"], fullName: ["Battle! Gym Leader (Johto) - Gold/Silver/Crystal", "Battle! Gym Leader (Johto) - HeartGold/SoulSilver"], type: "event", region: "Johto",
    fileUrl: ["https://vgmsite.com/soundtracks/pokemon-gold-silver-crystal/ltyjuezo/042%20Battle%21%20Gym%20Leader%20%28Johto%29.mp3", "https://vgmsite.com/soundtracks/pokemon-heartgold-and-soulsilver-music-super-complete/mqeqitakqm/1-43%20Battle%21%20Gym%20Leader%20%28Johto%29.mp3"],
    imgUrl: ["https://docs.google.com/uc?export=download&id=14v_H3YQQTXNsNntrFY3meoXJaHU6PtZA", "https://docs.google.com/uc?export=download&id=1ZqgvKdK0HXLrazpZO50IGED1NaqMs9qY", "https://docs.google.com/uc?export=download&id=1HWKHCqEgM9inWxGSBfvBssC_29D2yL7c", "https://docs.google.com/uc?export=download&id=1NgfvcxUipTfsViL9GNrA_f5xs5fu1813", "https://docs.google.com/uc?export=download&id=1f_hWaW1KwVxDd5vwiviQyNRXVbO4luLK", "https://docs.google.com/uc?export=download&id=1HEM1ZPp76TRgMzhU_BBnyAyqz-s1rmXm", "https://docs.google.com/uc?export=download&id=1lxxEx66kQTfdFUr_PrlV671qBwuiYlhH", "https://docs.google.com/uc?export=download&id=1s7DTOgFk0Xv689Hs0L5mZ4yytQ4RyKUH"] },
    { label: "Team Rocket", answers: ["rocket", "team rocket"], fullName: ["Battle! (Team Rocket) - Gold/Silver", "Battle! Team Rocket - HeartGold/SoulSilver"], type: "event", region: "Kanto/Alola",
    fileUrl: ["https://vgmsite.com/soundtracks/pokemon-gold-silver-crystal/lzjclaip/033%20Battle%21%20Team%20Rocket.mp3","https://vgmsite.com/soundtracks/pokemon-heartgold-and-soulsilver-music-super-complete/cslqyfoxyn/1-35%20Battle%21%20Team%20Rocket.mp3"], 
    imgUrl: ["https://docs.google.com/uc?export=download&id=1wNwjKrK9qGmHvF9him5WZPMt6QDp8m5y"] },
    { label: "Team Rainbow Rocket", answers: ["rocket", "team rocket", "rainbow rocket", "team rainbow rocket"], fullName: ["Battle! (Team Rainbow Rocket) - Ultra Sun/Ultra Moon"], type: "event", region: "Johto/Alola",
    fileUrl: ["https://vgmsite.com/soundtracks/pokemon-ultra-sun-and-pokemon-ultra-moon-battle-music-selection/bfbvwhyizp/07.%20Battle%21%20%28Team%20Rainbow%20Rocket%29.mp3"], 
    imgUrl: ["https://docs.google.com/uc?export=download&id=1sdeTc0A_1c2EQYbJl3NBpncPMEmYV-i-"] },
    { label: "Ho-Oh", answers: ["ho-oh", "ho oh"], fullName: ["Battle! Ho-Oh - HeartGold/SoulSilver", "Battle! (Ho-Oh) - Omega Ruby/Alpha Sapphire"], type: "pokemon", region: "Johto",
    fileUrl: ["https://vgmsite.com/soundtracks/pokemon-heartgold-and-soulsilver-music-super-complete/jvmrhfozac/1-87%20Battle%21%20Ho-Oh.mp3","https://vgmsite.com/soundtracks/pokemon-omega-ruby-and-alpha-sapphire-nintendo-3ds-gamerip/nqinnsny/111%20-%20Battle%21%20%28Ho-Oh%29.mp3"], 
    imgUrl: ["https://docs.google.com/uc?export=download&id=17UakII7lKpKBEyDLaJSi8HFfNbxq7ueh", "https://docs.google.com/uc?export=download&id=1xHD0VMe7rTAzG68sp6ZR8sBObLnpkU8e", "https://docs.google.com/uc?export=download&id=1Bu5N04fSYX0mlhFU2O_1s7wyEtbAeGfE"] },
    { label: "Lugia", answers: ["lugia"], fullName: ["Battle! Lugia - HeartGold/SoulSilver", "Battle! (Lugia) - Omega Ruby/Alpha Sapphire"], type: "pokemon", region: "Johto",
    fileUrl: ["https://vgmsite.com/soundtracks/pokemon-heartgold-and-soulsilver-music-super-complete/zgyvlqqedz/2-75%20Battle%21%20Lugia.mp3","https://vgmsite.com/soundtracks/pokemon-omega-ruby-and-alpha-sapphire-nintendo-3ds-gamerip/ybsmoopd/110%20-%20Battle%21%20%28Lugia%29.mp3"], 
    imgUrl: ["https://docs.google.com/uc?export=download&id=12RligR213aCGbs_jqUKU2Mm0tIzXAT-G", "https://docs.google.com/uc?export=download&id=1_zXSBuSISQK2u5YkrZOlD5fiKurTnY-Y", "https://docs.google.com/uc?export=download&id=13CggZ7GD7RIwX1mLtwuym9t2YoR3keku"] },
    { label: "Suicune/Entei/Raikou", answers: ["suicune", "entei", "raikou", "legendary dogs", "legendary beasts"], fullName: ["Battle! (Raikou-Entei-Suicune) - Omega Ruby/Alpha Sapphire"], type: "pokemon", region: "Johto",
    fileUrl: ["https://vgmsite.com/soundtracks/pokemon-omega-ruby-and-alpha-sapphire-nintendo-3ds-gamerip/ptvukakv/109%20-%20Battle%21%20%28Raikou-Entei-Suicune%29.mp3"], 
    imgUrl: ["https://docs.google.com/uc?export=download&id=1XTQLkRePLOSUI3UB41QRLf_en68BeSVS"] },
    //12
    //HOENN
    { label: "Steven", answers: ["steven", "steven stone", "champion steven", "hoenn champion"], fullName: ["Decisive Battle! Daigo - Ruby/Sapphire", "Battle! (Steven) - Omega Ruby/Alpha Sapphire"], type: "person", region: "Hoenn",
    fileUrl: ["https://vgmsite.com/soundtracks/pokemon-ruby-sapphire-music-super-complete/vehqovpu/2-47%20Decisive%20Battle%21%20Daigo.mp3","https://vgmsite.com/soundtracks/pokemon-omega-ruby-and-alpha-sapphire-nintendo-3ds-gamerip/bcznxmch/096%20-%20Battle%21%20%28Steven%29.mp3"], 
    imgUrl: ["https://docs.google.com/uc?export=download&id=1MjeYsHXqnrg8ooc_gV_9D_RMOiEP95Cx"] },
    { label: "Zinnia", answers: ["zinnia"], fullName: ["Battle! (Zinnia) - Omega Ruby/Alpha Sapphire"], type: "person", region: "Hoenn",
    fileUrl: ["https://vgmsite.com/soundtracks/pokemon-omega-ruby-and-alpha-sapphire-nintendo-3ds-gamerip/nrmptrda/104%20-%20Battle%21%20%28Zinnia%29.mp3"], 
    imgUrl: ["https://docs.google.com/uc?export=download&id=1gj5JMsyFbIDy9ennESXIWtSUJLTCkNgX"] },
    { label: "Maxie/Archie", answers: ["maxie", "archie", "magma leader", "aqua leader"], fullName: ["Battle! Team Magma Leader - Team Aqua Leader - Omega Ruby/Alpha Sapphire", "Battle! (Team MagmaAqua Boss Maxie & ​Archie) - Ultra Sun/Ultra Moon"], type: "person", region: "Hoenn",
    fileUrl: ["https://vgmsite.com/soundtracks/pokemon-omega-ruby-and-alpha-sapphire-nintendo-3ds-gamerip/dqpwdhtw/072%20-%20Battle%21%20%28Team%20Magma%20-%20Team%20Aqua%20Leader%29.mp3","https://vgmsite.com/soundtracks/pokemon-ultra-sun-and-pokemon-ultra-moon-battle-music-selection/xtcsbpqbxv/08.%20Battle%21%20%28Team%20MagmaAqua%20Boss%20Maxie%20%26%20Archie%29.mp3"], 
    imgUrl: ["https://docs.google.com/uc?export=download&id=1GXVIzABTbbv5Cs_cIYv8m1RL6jdcPvG4", "https://docs.google.com/uc?export=download&id=1gj5JMsyFbIDy9ennESXIWtSUJLTCkNgX"] },
    { label: "Brendan/May", answers: ["brendan", "may", "hoenn rival"], fullName: ["Battle! (Brendan-May) - Omega Ruby/Alpha Sapphire"], type: "person", region: "Hoenn",
    fileUrl: ["https://vgmsite.com/soundtracks/pokemon-omega-ruby-and-alpha-sapphire-nintendo-3ds-gamerip/ojnzihas/062%20-%20Battle%21%20%28Brendan-May%29.mp3"], 
    imgUrl: ["https://docs.google.com/uc?export=download&id=1lgx7Z7mUZQLsPa2We5tKAfapgDU512gh", "https://docs.google.com/uc?export=download&id=1RIxv6EEd0DdBrrEqKeeQUs_BWdVbze7U"] },
    { label: "Wally", answers: ["wally", "hoenn rival"], fullName: ["Rival's Theme - Omega Ruby/Alpha Sapphire"], type: "person", region: "Hoenn",
    fileUrl: ["https://vgmsite.com/soundtracks/pokemon-omega-ruby-and-alpha-sapphire-super-music-complete-nintendo-3ds/cahwuzbbqx/3-23%20Rival%27s%20Theme.mp3"], 
    imgUrl: ["https://docs.google.com/uc?export=download&id=1yx5IVDTEbtArYc6odaro5ffWf-SA4Kxo"] },
    { label: "Team Magma/Aqua", answers: ["team magma", "team aqua", "magma", "aqua", "hoenn villain team"], fullName: ["Battle! Team Aqua_Team Magma - Ruby/Sapphire", "Battle! Team Magma - Team Aqua - Omega Ruby/Alpha Sapphire"], type: "event", region: "Hoenn",
    fileUrl: ["https://vgmsite.com/soundtracks/pokemon-ruby-sapphire-music-super-complete/caftgfyr/1-25%20Battle%21%20Team%20Aqua%20_%20Team%20Magma.mp3","https://vgmsite.com/soundtracks/pokemon-omega-ruby-and-alpha-sapphire-nintendo-3ds-gamerip/awxkwice/025%20-%20Battle%21%20%28Team%20Magma%20-%20Team%20Aqua%29%20.mp3"], 
    imgUrl: ["https://docs.google.com/uc?export=download&id=1UpF98p-MM3e9p3PU4sTz7HYKgG6K-Fxl"] },
    { label: "Hoenn Elite Four", answers: ["hoenn elite four", "hoenn elite 4"], fullName: ["Battle! The Four Heavenly Kings - Ruby/Sapphire", "Battle! (Elite Four) - Omega Ruby/Alpha Sapphire"], type: "event", region: "Hoenn",
    fileUrl: ["https://vgmsite.com/soundtracks/pokemon-ruby-sapphire-music-super-complete/mzntbysy/2-45%20Battle%21%20The%20Four%20Heavenly%20Kings.mp3", "https://vgmsite.com/soundtracks/pokemon-omega-ruby-and-alpha-sapphire-nintendo-3ds-gamerip/owxfkhxc/094%20-%20Battle%21%20%28Elite%20Four%29.mp3"], 
    imgUrl: ["https://docs.google.com/uc?export=download&id=1TnBJpV6vY_bXZgIQuA_SVrXl5blf3-RB", "https://docs.google.com/uc?export=download&id=1wIw33wKYU6J3YnFVtyWka6eTf0qjKmXD", "https://docs.google.com/uc?export=download&id=1mZDWuU1IssaR9UXgLJPWTVuDWB-kkaCJ", "https://docs.google.com/uc?export=download&id=1Qnc2Chh9RoOc4hyALGZ6nrb6Aje7IFP0", "https://docs.google.com/uc?export=download&id=1L5ZhiX8prjwtFBxgQAjIT9YuF_reCSqe"] },
    { label: "Hoenn Gym", answers: ["hoenn gym"], fullName: ["Battle! Gym Leader - Ruby/Sapphire", "Battle! (Gym Leader) - Omega Ruby/Alpha Sapphire"], type: "event", region: "Hoenn",
    fileUrl: ["https://vgmsite.com/soundtracks/pokemon-ruby-sapphire-music-super-complete/fkcbohfk/1-50%20Battle%21%20Gym%20Leader.mp3","https://vgmsite.com/soundtracks/pokemon-omega-ruby-and-alpha-sapphire-nintendo-3ds-gamerip/uhndkkrh/048%20-%20Battle%21%20%28Gym%20Leader%29.mp3"], 
    imgUrl: ["https://docs.google.com/uc?export=download&id=1ZFftIUeuAoAQ0qDpyq2b4wpIC1bas7Cu", "https://docs.google.com/uc?export=download&id=1-C7FtJ3Tf4eNHURfC76XndAvGWTm82_p", "https://docs.google.com/uc?export=download&id=1IMsZfHS9D7jwBHDk5nkaXYrj-Mbjwf76", "https://docs.google.com/uc?export=download&id=1c6Io_YTA3DqYnRb4w8Eraxr3npUe3Tc1", "https://docs.google.com/uc?export=download&id=14LHNHKPlDnMynnMXPEF0_qxsh783qshN",  "https://docs.google.com/uc?export=download&id=1pPacVMD_n_QtDBQYuUcmHYzjvUT7KCu1", "https://docs.google.com/uc?export=download&id=10R75rzxFbtlkrdjbE5a9C3mLuFITDC1c", "https://docs.google.com/uc?export=download&id=15pxHtn6zSF6rFiYmAfwJGrSVUY2I2H3_"] },
    { label: "Deoxys", answers: ["deoxys"], fullName: ["Deoxys Battle! - FireRed/LeafGreen", "Battle! (Deoxys) - Omega Ruby/Alpha Sapphire"], type: "pokemon", region: "Hoenn",
    fileUrl: ["https://vgmsite.com/soundtracks/pokemon-firered-leafgreen-enhanced-soundtrack/lsncclgutk/71%20Deoxys%20Battle%21.mp3", "https://vgmsite.com/soundtracks/pokemon-omega-ruby-and-alpha-sapphire-nintendo-3ds-gamerip/actelfsk/105%20-%20Battle%21%20%28Deoxys%29.mp3"], 
    imgUrl: ["https://docs.google.com/uc?export=download&id=1BRbUWrv_bQdchux0DOplcAB1z9YjDqPU"] },
    { label: "Rayquaza/Kyogre/Groudon", answers: ["rayquaza", "kyogre", "groudon", "weather trio", "super ancient pokemon"], fullName: ["Battle! (Rayquaza) - Omega Ruby/Alpha Sapphire (Groudon/Kyogre theme is a variation)", "Battle! (Super Ancient Pokemon) - Omega Ruby/Alpha Sapphire", "Battle! (Super-Ancient Pokemon) - Emerald"], type: "pokemon", region: "Hoenn",
    fileUrl: ["https://vgmsite.com/soundtracks/pokemon-omega-ruby-and-alpha-sapphire-nintendo-3ds-gamerip/rhfilfee/102%20-%20Battle%21%20%28Rayquaza%29.mp3", "https://vgmsite.com/soundtracks/pokemon-omega-ruby-and-alpha-sapphire-nintendo-3ds-gamerip/lhpstbnl/078%20-%20Battle%21%20%28Super%20Ancient%20Pokemon%29.mp3", "https://vgmsite.com/soundtracks/pokemon-emerald-remastered-complete-original-soundtrack/jnlrbmtgpo/2-29%20-%20Battle%21%20%28Super-Ancient%20Poke%CC%81mon%29.mp3"], 
    imgUrl: ["https://docs.google.com/uc?export=download&id=1r2QN4aHx_3tVij1FqdqysLbmgJAF59Q9", "https://docs.google.com/uc?export=download&id=1BoUlNGkcG5sn70sebiHPWcL_7JTJIe1R"] },
    { label: "Regis", answers: ["regice", "registeel", "regirock", "regigigas", "legendary titans", "regidrago", "regieleki", "regis", "titans"], fullName: ["Battle! (Regirock~Regice~Registeel) - Emerald","Battle! ​(Regirock-Regice-Registeel-Regigigas) - Omega Ruby/Alpha Sapphire", "Battle! (Legendary Titans) - Sword/Shield (Crown Tundra)"], type: "pokemon", region: "Hoenn",
    fileUrl: ["https://vgmsite.com/soundtracks/pokemon-emerald-remastered-complete-original-soundtrack/eaybaqkbrg/2-38%20-%20Battle%21%20%28Regirock~Regice~Registeel%29.mp3","https://vgmsite.com/soundtracks/pokemon-omega-ruby-and-alpha-sapphire-nintendo-3ds-gamerip/zgtlmdtb/087%20-%20Battle%21%20%28Regirock-Regice-Registeel-Regigigas%29.mp3", "https://vgmsite.com/soundtracks/pokemon-sword-pokemon-shield-the-crown-tundra-super-music-collection/cbtniwyhbt/17%20-%20Battle%21%20%28Legendary%20Titans%29.mp3"], 
    imgUrl: ["https://docs.google.com/uc?export=download&id=15y5QREya-rf5Jm0jZfw8NXuLX-J4760l", "https://docs.google.com/uc?export=download&id=1P2V0wUfjj7q8N62eVK6o-AmSNfgd-4lc"] },
    //23
    //SINNOH/HISUI
    { label: "Cynthia", answers: ["cynthia", "champion cynthia", "sinnoh champion"], fullName: ["Battle! Champion - Diamond/Pearl", "Battle! (Champion—Sinnoh Version) - Black2/White2"], type: "person", region: "Sinnoh/Hisui",
    fileUrl: ["https://vgmsite.com/soundtracks/pokemon-diamond-and-pearl-super-music-collection/agmpuios/2-67%20Battle%21%20Champion.mp3", "https://vgmsite.com/soundtracks/pokemon-black-and-white-2-super-music-collection/osjxhkpojm/59%20Battle%21%20%28Champion%E2%80%94Sinnoh%20Version%29.mp3"], 
    imgUrl: ["https://docs.google.com/uc?export=download&id=1A9GwrJjNt10FXrzEZmjyIiP07Sl2E18T", "https://docs.google.com/uc?export=download&id=1yp4zUy6KYDRVypzC7NN5oQhqqCt6FF8_"] },
    { label: "Cyrus", answers: ["cyrus", "galatic boss"], fullName: ["Battle! Galaxy Gang Boss - Diamond/Pearl/Platinum", "Battle! (Team Galactic Boss Cyrus) - Ultra Sun/Ultra Moon"], type: "person", region: "Sinnoh/Hisui",
    fileUrl: ["https://vgmsite.com/soundtracks/pokemon-diamond-and-pearl-super-music-collection/exaaoiib/1-65%20Battle%21%20Galaxy%20Gang%20Boss.mp3","https://vgmsite.com/soundtracks/pokemon-ultra-sun-and-pokemon-ultra-moon-battle-music-selection/pcjpwqvahs/09.%20Battle%21%20%28Team%20Galactic%20Boss%20Cyrus%29.mp3"], 
    imgUrl: ["https://docs.google.com/uc?export=download&id=1796E-H4mlEXt4Wal0W_WyvZLvQcmEHSR"] },
    { label: "Barry", answers: ["barry", "sinnoh rival"], fullName: ["Battle! Rival - Diamond/Pearl"], type: "person", region: "Sinnoh/Hisui",
    fileUrl: ["https://vgmsite.com/soundtracks/pokemon-diamond-and-pearl-super-music-collection/kmmsdvnp/1-26%20Battle%21%20Rival.mp3"], 
    imgUrl: ["https://docs.google.com/uc?export=download&id=1ueBKSBuskG4cpPsGJJkidwDeHE79WWxF"] },
    { label: "Volo", answers: ["volo", "wielder volo", "pokemon wielder volo"], fullName: ["Battle! VS Wielder Volo - Legends: Arceus"], type: "person", region: "Sinnoh/Hisui",
    fileUrl: ["https://docs.google.com/uc?export=download&id=1LjzHAdJaV9JwuPUuXywbniezX629i6kI"], 
    imgUrl: ["https://docs.google.com/uc?export=download&id=1GqTizR2a7C7mmzIurqC7U_A3BdSr38kH"] },
    { label: "Sinnoh Gym", answers: ["sinnoh elite four", "sinnoh elite 4", "sinnoh gym"], fullName: ["Battle! Gym Leader - Diamond/Pearl (Elite 4 theme is a variation)"], type: "event", region: "Sinnoh/Hisui",
    fileUrl: ["https://vgmsite.com/soundtracks/pokemon-diamond-and-pearl-super-music-collection/lgyowmjx/1-32%20Battle%21%20Gym%20Leader.mp3"], 
    imgUrl: ["https://docs.google.com/uc?export=download&id=1e89qsBw-qol637REKR0eamAbcRW77Pb-", "https://docs.google.com/uc?export=download&id=1tfQaAzS-8UPu0qNC_2ztBRLsqO6FOrbe", "https://docs.google.com/uc?export=download&id=16k9BfAh2vujuugCgqiwFLe4l7JJeMFur", "https://docs.google.com/uc?export=download&id=1qb9FovHNEpV5YiR-VyHJfpvP7QUODnDO", "https://docs.google.com/uc?export=download&id=1nL_QnBahzUM5aDFS-aAELzArK9XlCrDg", "https://docs.google.com/uc?export=download&id=1QGQ5CFIfDK97XxPmq5G8Z_uAYicicl_c", "https://docs.google.com/uc?export=download&id=15IzqPvZ-MCuNHsGZQ2i6xRbmFbUdnswx", "https://docs.google.com/uc?export=download&id=1btRJKe0HJQUF7t1mxY-BL5-BB_CyfD1R"] },
    { label: "Sinnoh Elite Four", answers: ["sinnoh elite four", "sinnoh elite 4", "sinnoh gym"], fullName: ["Battle! The Heavenly Four - Diamond/Pearl (Gym theme is a variation)"], type: "event", region: "Sinnoh/Hisui",
    fileUrl: ["https://vgmsite.com/soundtracks/pokemon-diamond-and-pearl-super-music-collection/lxtkivcu/2-64%20Battle%21%20The%20Heavenly%20Four.mp3"], 
    imgUrl: ["https://docs.google.com/uc?export=download&id=1-psAYBXsLU7ysBA-WFrqNDxsQxzI8fQm"] },
    { label: "Team Galactic", answers: ["galactic", "team galactic", "galaxy gang", "galaxy"], fullName: ["Battle! Galaxy Gang - Diamond/Pearl"], type: "event", region: "Sinnoh/Hisui",
    fileUrl: ["https://vgmsite.com/soundtracks/pokemon-diamond-and-pearl-super-music-collection/uxtwotzp/1-41%20Battle%21%20Galaxy%20Gang.mp3"], 
    imgUrl: ["https://docs.google.com/uc?export=download&id=1quDQpL_Ks8GOtfWlylNMIrRO-dADtLd6"] },
    { label: "Dialga/Palkia", answers: ["dialga", "palkia", "time space duo", "creation duo"], fullName: ["Battle! Dialga _ Palkia - Diamond/Pearl", "Battle! VS Dialga Palkia - Legends: Arceus"], type: "pokemon", region: "Sinnoh/Hisui",
    fileUrl: ["https://vgmsite.com/soundtracks/pokemon-diamond-and-pearl-super-music-collection/tuefwfkn/1-71%20Battle%21%20Dialga%20_%20Palkia.mp3", "https://docs.google.com/uc?export=download&id=1kpsopGqLe6-7EVe1rm2Wji6fhlUOcL0X"], 
    imgUrl: ["https://docs.google.com/uc?export=download&id=1eWDxPPfOKZkPqEc_xVOyRHhvJfqVSjiE"] },
    { label: "Origin Dialga/Origin Palkia", answers: ["dialga", "palkia", "origin dialga", "origin palkia"], fullName: ["Battle! VS Origin Dialga-Palkia - Legends: Arceus"], type: "pokemon", region: "Sinnoh/Hisui",
    fileUrl: ["https://docs.google.com/uc?export=download&id=1970PcaPVMrm92__TgWZIo779wM6qSyFo"], 
    imgUrl: ["https://docs.google.com/uc?export=download&id=177qpB4auFg4PKUJoHAAxmwBsO3yM3gWZ", "https://docs.google.com/uc?export=download&id=1Ldh4HQPe2h5RJFFNoO4CAtgwEdjw38Wt"] },
    { label: "Giratina", answers: ["giratina"], fullName: ["Battle! Giratina - Platinum"], type: "pokemon", region: "Sinnoh/Hisui",
    fileUrl: ["https://vgmsite.com/soundtracks/pokemon-platinum/gjaxikjxlq/14%20Battle%21%20Giratina.mp3", "https://docs.google.com/uc?export=download&id=1F1HU_uIwL3F4dbeYbgLLwKoipXcpKaU2"], 
    imgUrl: ["https://docs.google.com/uc?export=download&id=1pyFPZPIgcUUTg2DljEIrZMvIDR5Vpbeq", "https://docs.google.com/uc?export=download&id=1oaw4GjGznFc9-0D6fKaCqeTZbEKXSK-4"] },
    { label: "Arceus", answers: ["arceus"], fullName: ["Battle! Arceus - Platinum", "Battle! VS Arceus - Legends: Arceus"], type: "pokemon", region: "Sinnoh/Hisui",
    fileUrl: ["https://vgmsite.com/soundtracks/pokemon-platinum/vhbablamjz/37%20Battle%21%20Arceus.mp3", "https://docs.google.com/uc?export=download&id=1YyJhudU5MsIjoDKSDPvjlh3T9lACCjXO"], 
    imgUrl: ["https://docs.google.com/uc?export=download&id=15FxuIDAzEJ6HbWxjhVv5RahHFnYB1o0C"] },
    { label: "Uxie/Azelf/Mesprit", answers: ["uxie", "mesprit", "azelf", "lake guardians", "lake spirits", "lake trio"], fullName: ["Battle! Uxie_Mesprit_Azelf - Diamond/Pearl", "Battle! VS Uxie-Azelf-Mesprit - Legends: Arceus"], type: "pokemon", region: "Sinnoh/Hisui",
    fileUrl: ["https://vgmsite.com/soundtracks/pokemon-diamond-and-pearl-super-music-collection/yotiwcau/2-37%20Battle%21%20Uxie%20_%20Mesprit%20_%20Azelf.mp3", "https://docs.google.com/uc?export=download&id=1lKDjQyhmAiYTJUMDTQhTNuzYg6Jhj_nP"], 
    imgUrl: ["https://docs.google.com/uc?export=download&id=17INh8bLB_gSbsuAmSksexPgKoqDCf0DA", "https://docs.google.com/uc?export=download&id=1FIYO_83jn1TXhYj3wYTM7n23a1NCIdgk"] },
    //35
    //UNOVA
    { label: "Alder", answers: ["alder", "champion alder", "unova champion"], fullName: ["Battle! Champion - Black/White"], type: "person", region: "Unova",
    fileUrl: ["https://vgmsite.com/soundtracks/pokemon-black-and-white/qubfuiyq/412%20Battle%21%20Champion.mp3"], 
    imgUrl: ["https://docs.google.com/uc?export=download&id=1lXOJ72Ct10hZHh_51zJ_aT63cM5DMYDL"] },
    { label: "Iris", answers: ["iris", "champion iris", "unova champion"], fullName: ["Battle! (Champion Iris) - Black2/White2"], type: "person", region: "Unova",
    fileUrl: ["https://vgmsite.com/soundtracks/pokemon-black-and-white-2-super-music-collection/pvnpndpirq/116%20Battle%21%20%28Champion%20Iris%29.mp3"], 
    imgUrl: ["https://docs.google.com/uc?export=download&id=1Zz2dwgUoSwBhyrI1Yk6Q-ryK_aWi9lj_"] },
    { label: "Cheren/Bianca", answers: ["cheren", "bianca", "unova rival"], fullName: ["Battle! Cheren/Bianca - Black/White"], type: "person", region: "Unova",
    fileUrl: ["https://vgmsite.com/soundtracks/pokemon-black-and-white/cvotespf/107%20Battle%21%20Cheren%20%C3%82%C2%B7%20Belle.mp3"], 
    imgUrl: ["https://docs.google.com/uc?export=download&id=15JmWMrh5rVLdRqHescAgml16j7dSlSF0", "https://docs.google.com/uc?export=download&id=1FdZE52niUhghSz6RO7VA5_KvJ2MHlWHy"] },
    { label: "N", answers: ["n", "natural", "natural harmonia gropius"], fullName: ["Battle! N - Black/White", "Decisive Battle! N - Black/White", "Battle! (N) - Black2/White2"], type: "person", region: "Unova",
    fileUrl: ["https://vgmsite.com/soundtracks/pokemon-black-and-white/kngbdrze/159%20Battle%21%20N.mp3", "https://vgmsite.com/soundtracks/pokemon-black-and-white/hoxedxry/237%20Decisive%20Battle%21%20N.mp3", "https://vgmsite.com/soundtracks/pokemon-black-and-white-2-super-music-collection/rpfprxnlry/100%20Battle%21%20%28N%29.mp3"], 
    imgUrl: ["https://docs.google.com/uc?export=download&id=1tt39iwR5Fn5K9hBt9WW3JiuyCID33IrQ", "https://docs.google.com/uc?export=download&id=1G60DtsifaEiWbT83KTpkFIbJPe9jjP-i", "https://docs.google.com/uc?export=download&id=1NxZysa6Efg5U2WeOzOcUmtlVIa0W0nxW", "https://docs.google.com/uc?export=download&id=196io3KuKU__tYchkOvPsKKXEdleJbrF8", "https://docs.google.com/uc?export=download&id=1hr9Q9_WsW9pgJQyCChJl2s2Yea6d-U_b"] },
    { label: "Ghetsis", answers: ["ghetsis", "ghetsis harmonia gropius"], fullName: ["Battle! Ghetsis - Black/White", "Battle! (Ghetsis) - Black2/White2", "Battle! (Team Plasma Boss Ghetsis) - Ultra Sun/Ultra Moon"], type: "person", region: "Unova",
    fileUrl: ["https://vgmsite.com/soundtracks/pokemon-black-and-white/ecyjqtkx/239%20Battle%21%20Geechisu.mp3", "https://vgmsite.com/soundtracks/pokemon-black-and-white-2-super-music-collection/bdheaesweb/95%20Battle%21%20%28Ghetsis%29.mp3", "https://vgmsite.com/soundtracks/pokemon-ultra-sun-and-pokemon-ultra-moon-battle-music-selection/vbigkkvnfo/10.%20Battle%21%20%28Team%20Plasma%20Boss%20Ghetsis%29.mp3"], 
    imgUrl: ["https://docs.google.com/uc?export=download&id=1nM_AjRSnCAa_CH2s6omEgbR6KXfTU784", "https://docs.google.com/uc?export=download&id=1JgeQYsLkfAhwzyD_BXfdNWpe02DCi-Sh"] },
    { label: "Colress", answers: ["colress"], fullName: ["Battle! (Colress) - Black2/White2"], type: "person", region: "Unova",
    fileUrl: ["https://vgmsite.com/soundtracks/pokemon-black-and-white-2-super-music-collection/ebtjzrnkaw/89%20Battle%21%20%28Colress%29.mp3"], 
    imgUrl: ["https://docs.google.com/uc?export=download&id=1amy2MJZ2bt4vaxXkfC2MY3zcQCX_elBU"] },
    { label: "Hugh", answers: ["hugh", "unova rival"], fullName: ["Battle! (Rival) - Black2/White2"], type: "person", region: "Unova",
    fileUrl: ["https://vgmsite.com/soundtracks/pokemon-black-and-white-2-super-music-collection/ytebskcpwi/11%20Battle%21%20%28Rival%29.mp3"], 
    imgUrl: ["https://docs.google.com/uc?export=download&id=1dG34G76JfIMngcMnbX-RsEYQ6kFSJTMZ"] },
    { label: "Unova Gym", answers: ["unova gym"], fullName: ["Battle! Gym Leader - Black/White", "Battle! (Gym Leader) - Black2/White2"], type: "event", region: "Unova",
    fileUrl: ["https://vgmsite.com/soundtracks/pokemon-black-and-white/kyazxsne/144%20Battle%21%20Gym%20Leader.mp3", "https://vgmsite.com/soundtracks/pokemon-black-and-white-2-super-music-collection/plczmlutbe/47%20Battle%21%20%28Gym%20Leader%29.mp3"], 
    imgUrl: ["https://docs.google.com/uc?export=download&id=1DVEg4wmFTYlmauRUEcnXQ_soGFp_MW39"] },
    { label: "Unova Elite Four", answers: ["unova elite four", "unova elite 4"], fullName: ["Battle! Elite Four - Black/White"], type: "event", region: "Unova",
    fileUrl: ["https://vgmsite.com/soundtracks/pokemon-black-and-white/jxinhmfq/229%20Battle%21%20Elite%20Four.mp3"], 
    imgUrl: ["https://docs.google.com/uc?export=download&id=1COQt2NqISBeUOLT9cMuFheLg4NFyFyXg", "https://docs.google.com/uc?export=download&id=12WB0MvSRwermDHfOXbxv8oiwo79Ojiie", "https://docs.google.com/uc?export=download&id=1UUrW_FAMVMFxw0hqBZZno0tJiHt0G1gs", "https://docs.google.com/uc?export=download&id=1HakWNwcgO2aW6B1pF4SHRdCLsth9u271", "https://docs.google.com/uc?export=download&id=1M5xDpcUhNAdtBXQ8bdvsbKTLY4XHOA71"] },
    { label: "Team Plasma", answers: ["team neo plasma", "neo plasma", "plasma", "team plasma"], fullName: ["Battle! Team Plasma - Black/White (Plasma theme in Black2/White2 is a variation)"], type: "event", region: "Unova",
    fileUrl: ["https://vgmsite.com/soundtracks/pokemon-black-and-white/fzoruihy/134%20Battle%21%20Team%20Plasma.mp3"], 
    imgUrl: ["https://docs.google.com/uc?export=download&id=1-RvmwW67D3Q6Zl781BAF-0w4FAOBTlPl"] },
    { label: "Neo Plasma", answers: ["team neo plasma", "neo plasma", "plasma", "team plasma"], fullName: ["Battle! Team Plasma - Black2/White2 (Plasma theme in Black/White is a variation)"], type: "event", region: "Unova",
    fileUrl: ["https://vgmsite.com/soundtracks/pokemon-black-and-white-2-super-music-collection/imhirmpzua/81%20Battle%21%20%28Team%20Plasma%29.mp3"], 
    imgUrl: ["https://docs.google.com/uc?export=download&id=1rG39q3O0ldwecnRBx3NG3Xm4OHpPYCP6"] },
    { label: "Reshiram/Zekrom", answers: ["tao trio", "reshiram", "zekrom", "kyurem"], fullName: ["Battle! Reshiram/Zekrom - Black/White (Kyurem theme is a variation)"], type: "pokemon", region: "Unova",
    fileUrl: ["https://vgmsite.com/soundtracks/pokemon-black-and-white/txuzxxkf/236%20Battle%21%20Reshiram%20%C3%82%C2%B7%20Zekrom.mp3"], 
    imgUrl: ["https://docs.google.com/uc?export=download&id=1_HCObjXMHDx3Bompl5UnHFJEG1BfTQOL"] },
    { label: "Kyurem", answers: ["tao trio", "reshiram", "zekrom", "kyurem"], fullName: ["Battle! Kyurem - Black/White (Reshiram/Zekrom theme is a variation)"], type: "pokemon", region: "Unova",
    fileUrl: ["https://vgmsite.com/soundtracks/pokemon-black-and-white/wbvgwfnf/410%20Battle%21%20Kyurem.mp3"], 
    imgUrl: ["https://docs.google.com/uc?export=download&id=1j3jSSd1tP9uJpaqr_nYELBLdhiNlmPXN"] },
    { label: "Black Kyurem/White Kyurem", answers: ["black kyurem", "white kyurem", "kyurem-white", "kyurem-black", "kyurem"], fullName: ["Battle! (Black Kyurem/White Kyurem) - Black2/White2"], type: "pokemon", region: "Unova",
    fileUrl: ["https://vgmsite.com/soundtracks/pokemon-black-and-white-2-super-music-collection/zoxhchrjhn/94%20Battle%21%20%28Black%20Kyurem_White%20Kyure.mp3"], 
    imgUrl: ["https://docs.google.com/uc?export=download&id=1j3jSSd1tP9uJpaqr_nYELBLdhiNlmPXN", "https://docs.google.com/uc?export=download&id=1ZQYR3DjdAVHW4wk-1m06umLqWFTtE33x"]},
    //49
    //KALOS
    { label: "Diantha", answers: ["dianta", "champion diantha", "kalos champion"], fullName: ["Battle! (Champion) - X/Y"], type: "person", region: "Kalos",
    fileUrl: ["https://vgmsite.com/soundtracks/pokemon-x-y/gdwoyyvjen/120%20Battle%21%20%28Champion%29.mp3"], 
    imgUrl: ["https://docs.google.com/uc?export=download&id=1-v1W-Z_YFaP7AzJHI_oYAXoOGJDN3m8Z"] },
    { label: "Lysandre", answers: ["lysandre", "team flare boss", "team flare boss lysandre"], fullName: ["Battle! (Lysandre) - X/Y", "Battle! (Team Flare Boss Lysandre) - Ultra Sun/Ultra Moon"], type: "person", region: "Kalos",
    fileUrl: ["https://vgmsite.com/soundtracks/pokemon-x-y/bnkkrwlsiv/104%20Battle%21%20%28Lysandre%29.mp3", "https://vgmsite.com/soundtracks/pokemon-ultra-sun-and-pokemon-ultra-moon-battle-music-selection/txsdgelhpz/12.%20Battle%21%20%28Team%20Flare%20Boss%20Lysandre%29.mp3"], 
    imgUrl: ["https://docs.google.com/uc?export=download&id=1KRdrRFv4V7B6sE05jypwRuUjww5yMaL_", "https://docs.google.com/uc?export=download&id=1VG7q-2SGwjA5dXcIHmlLEgKi2_SdlwQY", "https://docs.google.com/uc?export=download&id=17Fb_h3Hs1sIzE9gyfnQB0HiTwsUf9jL2"] },
    { label: "Kalos Rivals", answers: ["tierno", "shauna", "trevor", "kalos rival", "kalos rivals", "kalos friend", "kalos friends"], fullName: ["Battle! (Friend) - X/Y"], type: "person", region: "Kalos",
    fileUrl: ["https://vgmsite.com/soundtracks/pokemon-x-y/xbjqottbks/11%20Battle%21%20%28Friend%29.mp3"], 
    imgUrl: ["https://docs.google.com/uc?export=download&id=1eSmmzoeEWs3waAIlFRlWgdKbU4NO2v9H"] },
    { label: "Korrina", answers: ["korrina", "kalos gym"], fullName: ["Battle! (Successor Korrina) - X/Y (variation of gym theme)"], type: "person", region: "Kalos",
    fileUrl: ["https://vgmsite.com/soundtracks/pokemon-x-y/chkklxsies/72%20Battle%21%20%28Successor%20Korrina%29.mp3"], 
    imgUrl: ["https://docs.google.com/uc?export=download&id=1F3Q4F9CoXU3X8NERJ7pi2rQknVHxlJ4_"] },
    { label: "Kalos Gym", answers: ["korrina", "kalos gym"], fullName: ["Battle! (Gym Leader) - X/Y"], type: "event", region: "Kalos",
    fileUrl: ["https://vgmsite.com/soundtracks/pokemon-x-y/hcrtpjrhyj/29%20Battle%21%20%28Gym%20Leader%29.mp3"], 
    imgUrl: ["https://docs.google.com/uc?export=download&id=1tmIJjca0lwa8wb22FcuE0oy4FbFyyGnm"] },
    { label: "Kalos Elite Four", answers: ["kalos elite four", "kalos elite 4"], fullName: ["Battle! (Elite Four) - Kalos"], type: "event", region: "Kalos",
    fileUrl: ["https://vgmsite.com/soundtracks/pokemon-x-y/nrpxxobgls/119%20Battle%21%20%28Elite%20Four%29.mp3"], 
    imgUrl: ["https://docs.google.com/uc?export=download&id=1HuYmkqU3x8t0jfvFre_cGCFEZJqGaX8r", "https://docs.google.com/uc?export=download&id=1McQOq-42zZQZWMTemQkJHWFUL_bxZHaC", "https://docs.google.com/uc?export=download&id=1WDel-9x78Va88XE42brbbJD29J3ITEtz", "https://docs.google.com/uc?export=download&id=1BkupneFOS5se0BaYYWUroSzZd2x1xTgd"] },
    { label: "Team Flare", answers: ["flare", "team flare"], fullName: ["Battle! (Team Flare) - X/Y"], type: "event", region: "Kalos",
    fileUrl: ["https://vgmsite.com/soundtracks/pokemon-x-y/enngphjwlf/80%20Battle%21%20%28Team%20Flare%29.mp3"], 
    imgUrl: ["https://docs.google.com/uc?export=download&id=13q60VhGcQNUcn8YSOA_NK5W61g54QCa7"] },
    { label: "Xerneas/Yveltal/Zygarde", answers: ["xerneas", "yveltal", "zygarde"], fullName: ["Battle! (Xerneas/Yveltal) - X/Y (shared with Zygarde)"], type: "pokemon", region: "Kalos",
    fileUrl: ["https://vgmsite.com/soundtracks/pokemon-x-y/nflvgehnvx/103%20Battle%21%20%28XerneasYveltal%29.mp3"], 
    imgUrl: ["https://docs.google.com/uc?export=download&id=1iNZUGrxzUmf8PlOqbG-3gVhiYs2VbrGL", "https://docs.google.com/uc?export=download&id=1UV97kapfZE-zB1SWPye_dsFOOVCI24Ip", "https://docs.google.com/uc?export=download&id=1mp_0dQjAG3Li57NoRAkT-uQPLErcCEQT", "https://docs.google.com/uc?export=download&id=1RydVpLwUo1dyjVemBKTExr0lcDL_ZwmZ", "https://docs.google.com/uc?export=download&id=1NmDON-a86H0XtG631tSgbjp_ntdHAXzK"] },
    //57
    //ALOLA
    { label: "Kukui", answers: ["kukui", "alola champion", "champion kukui"], fullName: ["The Battle at the Summit! - Sun/Moon"], type: "person", region: "Alola",
    fileUrl: ["https://vgmsite.com/soundtracks/pokemon-sun-moon-super-music-collection/ujmmijvwdr/151%20The%20Battle%20at%20the%20Summit%21.mp3"], 
    imgUrl: ["https://docs.google.com/uc?export=download&id=1l3WiovICuLCUoA_prTv0s2TwsB-tUSaW"] },
    { label: "Hau", answers: ["hau", "alola rival", "alola champion"], fullName: ["Battle! (Hau) - Sun/Moon", "Championship Battle! (Vs. Rival Hau) - Ultra Sun/Ultra Moon"], type: "person", region: "Alola",
    fileUrl: ["https://vgmsite.com/soundtracks/pokemon-sun-moon-super-music-collection/gwgddjchtn/18%20Battle%21%20%28Hau%29.mp3", "https://vgmsite.com/soundtracks/pokemon-ultra-sun-and-pokemon-ultra-moon-sound-selection/ymludjftnn/25%20-%20Championship%20Battle%21%20%28Vs.%20Rival%20Hau%29.mp3"], 
    imgUrl: ["https://docs.google.com/uc?export=download&id=12T_6gfeOZoDgDssdqhJj6VteDnbecMqV"] },
    { label: "Gladion", answers: ["gladion"], fullName: ["Battle! (Gladion) - Sun/Moon"], type: "person", region: "Alola",
    fileUrl: ["https://vgmsite.com/soundtracks/pokemon-sun-moon-super-music-collection/jxazjnqogk/81%20Battle%21%20%28Gladion%29.mp3"], 
    imgUrl: ["https://docs.google.com/uc?export=download&id=18VWps_Ypzm9NvKROvWv9WM8FWhq401HK", "https://docs.google.com/uc?export=download&id=1YoHNw6AXG5t20J7fjDppUK6LFcpM0XQ1"] },
    { label: "Lusamine", answers: ["lusamine", "aether president", "president lusamine", "aether president lusamine"], fullName: ["Battle! (Lusamine) - Sun/Moon"], type: "person", region: "Alola",
    fileUrl: ["https://vgmsite.com/soundtracks/pokemon-sun-moon-super-music-collection/orkdeapflc/122%20Battle%21%20%28Lusamine%29.mp3"], 
    imgUrl: ["https://docs.google.com/uc?export=download&id=12SLgxib7yfiDislYEU0JgmUFE5rDqNSb", "https://docs.google.com/uc?export=download&id=1_IFHxvVcJ2VVBju83swdqvuuL8iVb1F6"] },
    { label: "Mother Beast Lusamine", answers: ["lusamine", "aether president", "president lusamine", "aether president lusamine", "mother beast lusamine"], fullName: ["Showdown! (Lusamine) - Sun/Moon"], type: "person", region: "Alola",
    fileUrl: ["https://vgmsite.com/soundtracks/pokemon-sun-moon-super-music-collection/lobfpnimze/138%20Showdown%21%20%28Lusamine%29.mp3"], 
    imgUrl: ["https://docs.google.com/uc?export=download&id=1xD2qDJ0ozbK5tjXy_VNE0GIkZZAMi4Xj"] },
    { label: "Guzma", answers: ["guzma", "your boy", "your boi", "ya boi", "ya boy", "team skull boss", "team skull boss guzma"], fullName: ["Battle! (Team Skull Boss) - Sun/Moon"], type: "person", region: "Alola",
    fileUrl: ["https://vgmsite.com/soundtracks/pokemon-sun-moon-super-music-collection/jtwepayuhc/107%20Battle%21%20%28Team%20Skull%20Boss%29.mp3"], 
    imgUrl: ["https://docs.google.com/uc?export=download&id=12b-bk_8Tw5_UfempsBkLcMsRPQKyDI3U"] },
    { label: "Plumeria", answers: ["plumeria", "team skull admin", "skull admin"], fullName: ["Battle! (Team Skull Admin - Sun/Moon"], type: "person", region: "Alola",
    fileUrl: ["https://vgmsite.com/soundtracks/pokemon-sun-moon-super-music-collection/awtyyluhwi/96%20Battle%21%20%28Team%20Skull%20Admin%29.mp3"], 
    imgUrl: ["https://docs.google.com/uc?export=download&id=1Yejnbvzd7_JGGV2yCpdSyJxd_mZEjRsE"] },
    { label: "Totem Pokemon", answers: ["totem", "alola gym", "alola totem", "totem pokemon"], fullName: ["Battle! (Totem Pokémon) - Sun/Moon"], type: "event", region: "Alola",
    fileUrl: ["https://vgmsite.com/soundtracks/pokemon-sun-moon-super-music-collection/zaiyobmuiq/63%20Battle%21%20%28Totem%20Pok%C3%A9mon%29.mp3"], 
    imgUrl: ["https://docs.google.com/uc?export=download&id=1faJ-d_22oU1fDRS1vMdGfZM1rqhlA-i7", "https://docs.google.com/uc?export=download&id=1eSzNHTfwRRaXuc2GT9nBSQ7R3epOnDtn", "https://docs.google.com/uc?export=download&id=1zW71U7CMI0r5YI5YfWcvTFEtPw-TlRkT", "https://docs.google.com/uc?export=download&id=1rNMMYwKW9HvJ_buIVcnTfx65aD_sgYXy", "https://docs.google.com/uc?export=download&id=1jYxRpwlJVcu65VJOjj9OfhGSs7XPUg7M", "https://docs.google.com/uc?export=download&id=1BNkuwimN3RFbRbC1_uuRKn82JbBVthkG", "https://docs.google.com/uc?export=download&id=13BBHtEkHnmTq2UXC-VoUCk9Xi2XBbjq_", "https://docs.google.com/uc?export=download&id=1Cek0Uq0L_PR5eKgbR7zHNvDsgOoIDJNK"] },
    { label: "Kahuna", answers: ["kahuna", "island kahuna", "alola kahuna"], fullName: ["Battle! (Island Kahuna) - Sun/Moon"], type: "event", region: "Alola",
    fileUrl: ["https://vgmsite.com/soundtracks/pokemon-sun-moon-super-music-collection/spwbrtvqfg/68%20Battle%21%20%28Island%20Kahuna%29.mp3"], 
    imgUrl: ["https://docs.google.com/uc?export=download&id=13i1Ej64G6qjQ66mk7gwXrcHctNPRA9WR"] },
    { label: "Team Skull", answers: ["team skull", "skull"], fullName: ["Battle! (Team Skull) - Sun/Moon"], type: "event", region: "Alola",
    fileUrl: ["https://vgmsite.com/soundtracks/pokemon-sun-moon-super-music-collection/tgxprfcllj/58%20Battle%21%20%28Team%20Skull%29.mp3"], 
    imgUrl: ["https://docs.google.com/uc?export=download&id=1izSSMdUOFm1qePe2vgdq4fVZO7reYiOf"] },
    { label: "Aether Foundation", answers: ["aether foundation", "aether", "aether team", "team aether"], fullName: ["Battle! (Aether Foundation) - Sun/Moon"], type: "event", region: "Alola",
    fileUrl: ["https://vgmsite.com/soundtracks/pokemon-sun-moon-super-music-collection/jupvuybufv/117%20Battle%21%20%28Aether%20Foundation%29.mp3"], 
    imgUrl: ["https://docs.google.com/uc?export=download&id=1VKdygNX1wr03o6kmx8T8Ohwt-6FtFO-0"] },
    { label: "Alola Elite Four", answers: ["alola elite four", "alola elite 4"], fullName: ["Battle! (Elite Four) - Sun/Moon"], type: "event", region: "Alola",
    fileUrl: ["https://vgmsite.com/soundtracks/pokemon-sun-moon-super-music-collection/qkjxokqzqf/150%20Battle%21%20%28Elite%20Four%29.mp3"], 
    imgUrl: ["https://docs.google.com/uc?export=download&id=1ZcdtYhkFCWV-VDd0qdO7IJq6ESx2Wg3G", "https://docs.google.com/uc?export=download&id=1maUXftp-_iHqQLREp_uZ7mV3SUyDoLRy", "https://docs.google.com/uc?export=download&id=1hBDJhRtrpw2TGJjH1Yi9riAWw-b_L7Xy", "https://docs.google.com/uc?export=download&id=1jVSlvoS5PWyx1mQjm1rdD6RFxGmP58O1"] },
    { label: "Ultra Recon Squad", answers: ["recon squad", "ultra recon squad"], fullName: ["Battle! (Ultra Recon Squad) - Ultra Sun/Ultra Moon"], type: "event", region: "Alola",
    fileUrl: ["https://vgmsite.com/soundtracks/pokemon-ultra-sun-and-pokemon-ultra-moon-sound-selection/xperwmmidg/8%20-%20Battle%21%20%28Ultra%20Recon%20Squad%29.mp3"], 
    imgUrl: ["https://docs.google.com/uc?export=download&id=1tIXGfrENT1uCXqrF_DOb4LciB1VcouCs"] },
    { label: "Solgaleo/Lunala/Necroma", answers: ["solgaleo", "lunala", "necrozma", "light trio"], fullName: ["Battle! (Solgaleo-Lunala) - Sun/Moon (theme shared with regular Necroma)"], type: "pokemon", region: "Alola",
    fileUrl: ["https://vgmsite.com/soundtracks/pokemon-sun-moon-super-music-collection/falwiiauwy/142%20Battle%21%20%28Solgaleo%20-%20Lunala.mp3"], 
    imgUrl: ["https://docs.google.com/uc?export=download&id=11iDtLUIg91Be4qP4pXIC_sa7yvuBDHhr", "https://docs.google.com/uc?export=download&id=1dWoCQJyJCCmoxFosWzzToSIrEhODe_eW", "https://docs.google.com/uc?export=download&id=1YxSIhgFJRTZ1IfHJzLPjm7RN4EWW1E5L"] },
    { label: "Dawn Wings/Dusk Mane Necrozma", answers: ["necrozma", "dawn wings necrozma", "dusk mane necrozma"], fullName: ["Battle! (Dawn Wings Dusk Mane Necrozma) - Ultra Sun/Ultra Moon"], type: "pokemon", region: "Alola",
    fileUrl: ["https://vgmsite.com/soundtracks/pokemon-ultra-sun-and-pokemon-ultra-moon-sound-selection/cjimfcznsi/13%20-%20Battle%21%20%28Dusk%20Mane%20%20Dawn%20Wings%20Necrozma%29.mp3"], 
    imgUrl: ["https://docs.google.com/uc?export=download&id=1tcIwgGSUci5Bya8fVHvHyu8NezG_Zxpe"] },
    { label: "Ultra Necrozma", answers: ["ultra necrozma", "necrozma"], fullName: ["Battle! (Ultra Necrozma) - Ultra Sun/Ultra Moon"], type: "pokemon", region: "Alola",
    fileUrl: ["https://vgmsite.com/soundtracks/pokemon-ultra-sun-and-pokemon-ultra-moon-battle-music-selection/rnakgxvnfs/20.%20Battle%21%20%28Ultra%20Necrozma%29.mp3"], 
    imgUrl: ["https://docs.google.com/uc?export=download&id=1UfAYSc_aeBVLnnxpn3BiOpvPhZOfi-Tf"] },
    { label: "Ultra Beast", answers: ["ultra beasts", "ultra beast", "ub", "nihilego", "buzzwole", "pheromosa", "xurkitree", "celesteela", "kartana", "guzzlord", "poipole", "naganadel", "stakataka", "blacephalon"], fullName: ["Battle! (Ultra Beast) - Sun/Moon"], type: "pokemon", region: "Alola",
    fileUrl: ["https://vgmsite.com/soundtracks/pokemon-sun-moon-super-music-collection/udtkutwnkk/102%20Battle%21%20%28Ultra%20Beast%29.mp3"], 
    imgUrl: ["https://docs.google.com/uc?export=download&id=18ZPDFbKVtOveilg36muru4JQfaPUoic5"] },
    { label: "Tapus", answers: ["tapu", "tapu fini", "tapu koko", "tapu fini", "tapu lele", "tapu bulu", "guardian deities", "tapus", "island guardians"], fullName: ["Battle! (Tapu) - Sun/Moon"], type: "pokemon", region: "Alola",
    fileUrl: ["https://vgmsite.com/soundtracks/pokemon-sun-moon-super-music-collection/uksejyadbg/154%20Battle%21%20%28Tapu%29.mp3"], 
    imgUrl: ["https://docs.google.com/uc?export=download&id=11iDtLUIg91Be4qP4pXIC_sa7yvuBDHhr", "https://docs.google.com/uc?export=download&id=1UfAYSc_aeBVLnnxpn3BiOpvPhZOfi-Tf", "https://docs.google.com/uc?export=download&id=1S3Vtnb2L4I1Scekpx4TdOm9Knlm8hyPo", "https://docs.google.com/uc?export=download&id=1ZZsZrkPHCiRdyDGr2vQzaiFt1LnxvYkx"] },
    //75
    //GALAR
    { label: "Hop", answers: ["hop"], fullName: ["Battle! (Hop) - Sword/Shield", "Showdown! (Hop) - Sword/Shield"], type: "person", region: "Galar",
    fileUrl: ["https://vgmsite.com/soundtracks/pokemon-sword-and-shield-official-soundtrack/mxvamgropt/09.%20Battle%21%20%28Hop%29.mp3", "https://vgmsite.com/soundtracks/pokemon-sword-shield-ost/steumiohsh/90%20-%20Showdown%21%20%28Hop%29.mp3"], 
    imgUrl: ["https://docs.google.com/uc?export=download&id=1xpfGuYujc8nVUZs4Z6nyPKoONYmQT9iQ", "https://docs.google.com/uc?export=download&id=1lpJQeGngysGgDZdK65f9poS62A9YHmMC", "https://docs.google.com/uc?export=download&id=1ep3wpUA_IJeC47V8qJTuSF2OHDGYPXs2"] },
    { label: "Leon", answers: ["leon", "champion leon"], fullName: ["Battle! (Champion Leon) - Sword/Shield"], type: "person", region: "Galar",
    fileUrl: ["https://vgmsite.com/soundtracks/pokemon-sword-shield-ost/iftclupbox/108%20-%20Battle%21%20%28Champion%20Leon%29.mp3"], 
    imgUrl: ["https://docs.google.com/uc?export=download&id=19PQtp4y1opAZU4mfPjedZtT4njhZegUA", "https://docs.google.com/uc?export=download&id=1m99XVYnA64IfaMgViFwL2clLHfBkd-Uy", "https://docs.google.com/uc?export=download&id=1IKRvThjA51ceSdOsboggnEctFX1NGgt6", "https://docs.google.com/uc?export=download&id=16FY8DzQ5pwJljTZv5XKuOagPXzgJidol"] },
    { label: "Marnie", answers: ["marnie"], fullName: ["Battle! (Marnie) - Sword/Shield", "Showdown! (Marnie) - Sword/Shield"], type: "person", region: "Galar",
    fileUrl: ["https://vgmsite.com/soundtracks/pokemon-sword-shield-ost/muncqyylos/68%20-%20Battle%21%20%28Marnie%29.mp3", "https://vgmsite.com/soundtracks/pokemon-sword-shield-ost/ikxnfrxefo/89%20-%20Showdown%21%20%28Marnie%29.mp3"], 
    imgUrl: ["https://docs.google.com/uc?export=download&id=1aFZVHcd2YZ3nKT1AmFq0E7ctfMU-0sxe", "https://docs.google.com/uc?export=download&id=1Nb7nYImw5zsSKBLxEaHM_nEROxCxbtmH", "https://docs.google.com/uc?export=download&id=13m1Zm36Y8ZzswvxSH3Oln1RqJIrDTnRw"] },
    { label: "Bede", answers: ["bede"], fullName: ["Battle! (Bede) - Sword/Shield"], type: "person", region: "Galar",
    fileUrl: ["https://vgmsite.com/soundtracks/pokemon-sword-shield-ost/sjjaegxlix/50%20-%20Battle%21%20%28Bede%29.mp3"], 
    imgUrl: ["https://docs.google.com/uc?export=download&id=1upHtB3rQeyQ_gTBRTVrZndw0_JdAKFUn", "https://docs.google.com/uc?export=download&id=1gZmYpqujBCTOabSXEQ-BGU7Yx72C2lUS", "https://docs.google.com/uc?export=download&id=1cYl-82EpkgEDmta8IxE_47SfXSSXKAXt"] },
    { label: "Oleana", answers: ["oleana"], fullName: ["Battle! (Oleana) - Sword/Shield"], type: "person", region: "Galar",
    fileUrl: ["https://vgmsite.com/soundtracks/pokemon-sword-shield-ost/xofxidviuq/93%20-%20Battle%21%20%28Oleana%29.mp3"], 
    imgUrl: ["https://docs.google.com/uc?export=download&id=1e2mCRja6claq8rPBmp0A5sv2kwu9VNpO"] },
    { label: "Rose", answers: ["rose", "chairman rose"], fullName: ["Battle! (Chairman Rose) - Sword/Shield"], type: "person", region: "Galar",
    fileUrl: ["https://vgmsite.com/soundtracks/pokemon-sword-shield-ost/ylcytqnqij/102%20-%20Battle%21%20%28Chairman%20Rose%29.mp3"], 
    imgUrl: ["https://docs.google.com/uc?export=download&id=1HvP8cliVSEzUiUY5d1TaYfbVYbHx03G1", "https://docs.google.com/uc?export=download&id=1iBSBr_bXTWIaok-88GBhM4HZUkqUuSOU"] },
    { label: "Peony", answers: ["peony"], fullName: ["Battle! (Peony) - Sword/Shield (Crown Tundra)"], type: "person", region: "Galar",
    fileUrl: ["https://vgmsite.com/soundtracks/pokemon-sword-pokemon-shield-the-crown-tundra-super-music-collection/oibnxepcig/03%20-%20Battle%21%20%28Peony%29.mp3"], 
    imgUrl: ["https://docs.google.com/uc?export=download&id=1km22us__L1ri-frgbdLtyxCDkqBPX3FC", "https://docs.google.com/uc?export=download&id=1M-IVsIMSzTAh462A-PtEh7VtcjkCZZJ8"] },
    { label: "Piers", answers: ["piers"], fullName: ["Battle! (Gym Leader Piers) - Sword/Shield"], type: "person", region: "Galar",
    fileUrl: ["https://vgmsite.com/soundtracks/pokemon-sword-shield-ost/mvfmspagta/83%20-%20Battle%21%20%28Gym%20Leader%20Piers%29.mp3"], 
    imgUrl: ["https://docs.google.com/uc?export=download&id=1-T2JBqqwTowqV6wJEVMsqsJWUOlNLnii", "https://docs.google.com/uc?export=download&id=1PeYtoUGwMoYcQSHBEIty0pq5XI9A6rNH"] },
    { label: "Mustard", answers: ["mustard"], fullName: ["Battle! (Mustard) - Sword/Shield (Isle of Armour)", "Final Battle! (Mustard) - Sword/Shield (Isle of Armour)"], type: "person", region: "Galar",
    fileUrl: ["https://vgmsite.com/soundtracks/pokemon-sword-shield-the-isle-of-armor-super-music-collection/exytpmfmqo/09.%20Battle%21%20%28Mustard%29.mp3", "https://vgmsite.com/soundtracks/pokemon-sword-shield-the-isle-of-armor-super-music-collection/moqbpsoquy/14.%20Final%20Battle%21%20%28Mustard%29.mp3"], 
    imgUrl: ["https://docs.google.com/uc?export=download&id=1f4kTp7OAFFnuGY5eL7H9JyoX9cCTko5u", "https://docs.google.com/uc?export=download&id=1-IXnzm2B-0WzE1L-4a23L0n_fKCY2Dry", "https://docs.google.com/uc?export=download&id=1_l-iVkYuQAGPtKz5OTrYBuhFQH9fgfWA"] },
    { label: "Avery", answers: ["avery"], fullName: ["Battle! (Avery) - Sword/Shield (Isle of Armour)"], type: "person", region: "Galar",
    fileUrl: ["https://vgmsite.com/soundtracks/pokemon-sword-shield-the-isle-of-armor-super-music-collection/juvcsyhidk/03.%20Battle%21%20%28Avery%29.mp3"], 
    imgUrl: ["https://docs.google.com/uc?export=download&id=1GoTD_6hTi1IWWfXVoZH1u6UzrVpbSXfv", "https://docs.google.com/uc?export=download&id=14UgdLLfORvbeOaYgypD-mXW2td_XFBTW"] },
    { label: "Klara", answers: ["klara"], fullName: ["Battle! (Klara) - Sword/Shield (Isle of Armour)"], type: "person", region: "Galar",
    fileUrl: ["https://vgmsite.com/soundtracks/pokemon-sword-shield-the-isle-of-armor-super-music-collection/ujnfmwpwlr/05.%20Battle%21%20%28Klara%29.mp3"], 
    imgUrl: ["https://docs.google.com/uc?export=download&id=1dNjfiA4TrMYcPuCExkx_NozxEJFZ3fat", "https://docs.google.com/uc?export=download&id=1QCDeRxsOisK2kFVM7jVq4BEdkNPqjzBC"] },
    { label: "Galar Gym", answers: ["galar gym", "galar league", "galar tournament"], fullName: ["Battle! (Gym Leader) - Sword/Shield", "Battle! (Pokemon League Tournament) - Sword/Shield"], type: "event", region: "Galar",
    fileUrl: ["https://vgmsite.com/soundtracks/pokemon-sword-shield-ost/pnzlhjcndt/60%20-%20Battle%21%20%28Gym%20Leader%29.mp3", "https://vgmsite.com/soundtracks/pokemon-sword-shield-ost/vlmfxbhinb/95%20-%20Battle%21%20%28Pok%C3%A9mon%20League%20Tournament%29.mp3"], 
    imgUrl: ["https://docs.google.com/uc?export=download&id=1BeJgORNV1BUE7OQw79BTXg9h0_EPAOSt", "https://docs.google.com/uc?export=download&id=1-qnEb6V_yXxAw76N9RfTQe4hKNwifs08", "https://docs.google.com/uc?export=download&id=1GsW0-I96-RjKeX7RJbMe3OHcUmV9RGOe", "https://docs.google.com/uc?export=download&id=16NFk99esqj1oyZAOLhNCQ321OTvxaAgI", "https://docs.google.com/uc?export=download&id=1R7grh8l9oVrKPJ7MK86a0H7UY9Nrs4TH", "https://docs.google.com/uc?export=download&id=1YaJ_TG41K-yBio6m0Am7iNcZREue2PVC", "https://docs.google.com/uc?export=download&id=1upjAz_B-nz3UFNT_Iyyt5ItdTJcrYRND", "https://docs.google.com/uc?export=download&id=1L5nSXzpPC0YwewfNRqwhxQ134n3cddC9", "https://docs.google.com/uc?export=download&id=1tf2BeGMeKCYHR54wQL_ixKnsU_kQFUou"] },
    { label: "Team Yell", answers: ["yell", "team yell"], fullName: ["Battle! (Team Yell) - Sword/Shield"], type: "person", region: "Galar",
    fileUrl: ["https://vgmsite.com/soundtracks/pokemon-sword-shield-ost/wekqfbpnoa/41%20-%20Battle%21%20%28Team%20Yell%29.mp3"], 
    imgUrl: ["https://docs.google.com/uc?export=download&id=1scbMRImg_1RmwSEQCN_YQKPC0-k9nRs1", "https://docs.google.com/uc?export=download&id=19htZ4kiGMSMXnHQfSL3RlUQUvzKq4WdX"] },
    { label: "Zacian/Zamazenta", answers: ["zacian", "zamazenta", "mysterious being", "hero duo", "sword wolf", "shield wolf"], fullName: ["Battle! (Mysterious Being) - Sword/Shield", "Battle! (Zacian Zamazenta) - Sword/Shield"], type: "pokemon", region: "Galar",
    fileUrl: ["https://vgmsite.com/soundtracks/pokemon-sword-shield-ost/hwhqiodlyg/13%20-%20Battle%21%20%28Mysterious%20Being%29.mp3", "https://vgmsite.com/soundtracks/pokemon-sword-shield-ost/zeajmxdivc/112%20-%20Battle%21%20%28Zacian%20%20Zamazenta%29.mp3"], 
    imgUrl: ["https://docs.google.com/uc?export=download&id=1uxlJkZ3GkgxkDc5Raz2NAbsKkaG8W71S", "https://docs.google.com/uc?export=download&id=13ig080eZ6TNpF3MKKdf567trY5PXZoyo", "https://docs.google.com/uc?export=download&id=1b1x0ykm_1Pe8SX5ahJtcNScijfGGn21n"] },
    { label: "Eternatus", answers: ["eternatus"], fullName: ["Battle! (Eternatus) ~ Phase 1 - Sword/Shield", "Battle! (Eternatus) ~ Phase 2 - Sword/Shield", "Battle! (Eternatus) ~ Phase 3 - Sword/Shield"], type: "pokemon", region: "Galar",
    fileUrl: ["https://vgmsite.com/soundtracks/pokemon-sword-shield-ost/exlvqorrgw/104%20-%20Battle%21%20%28Eternatus%29%20~%20Phase%201.mp3", "https://vgmsite.com/soundtracks/pokemon-sword-shield-ost/yedlwzkhmy/105%20-%20Battle%21%20%28Eternatus%29%20~%20Phase%202.mp3", "https://vgmsite.com/soundtracks/pokemon-sword-shield-ost/hplivceuey/106%20-%20Battle%21%20%28Eternatus%29%20~%20Phase%203.mp3"], 
    imgUrl: ["https://docs.google.com/uc?export=download&id=1__jWxQX1yQ9L6rzyf2443CgaEhJa5AZc", "https://docs.google.com/uc?export=download&id=18w8p02JnyyopF3TdLJGrA1P0VfCAk49C", "https://docs.google.com/uc?export=download&id=1LANRFT7YFbtnR30e9twnLd2r92NdU5sB"] },
    { label: "Spectrier/Glastrier", answers: ["glastrier", "spectrier"], fullName: ["Battle! (Glastrier Spectrier) - Sword/Shield (Crown Tundra)"], type: "pokemon", region: "Galar",
    fileUrl: ["https://vgmsite.com/soundtracks/pokemon-sword-pokemon-shield-the-crown-tundra-super-music-collection/nogdyzfdzn/13%20-%20Battle%21%20%28Glastrier%20%20Spectrier%29.mp3"], 
    imgUrl: ["https://docs.google.com/uc?export=download&id=1PTVxo46PDAKxT34de4z4hAUQ6MN-GqTh", "https://docs.google.com/uc?export=download&id=1r61pY5ChysPU-4ETXxIbKfQYARrquL8V"] },
    { label: "Calyrex", answers: ["calyrex"], fullName: ["Battle! (Calyrex) - Sword/Shield (Crown Tundra)"], type: "pokemon", region: "Galar",
    fileUrl: ["https://vgmsite.com/soundtracks/pokemon-sword-pokemon-shield-the-crown-tundra-super-music-collection/bbjmcexjaf/11%20-%20Battle%21%20%28Calyrex%29.mp3"], 
    imgUrl: ["https://docs.google.com/uc?export=download&id=1YkLG06p1endj6_I0FdccBvNXIGbbk7Ex"] },
    { label: "Ice Rider/Shadow Rider Calyrex", answers: ["calyrex", "ice rider calyrex", "shadow rider calyrex", "rider calyrex"], fullName: ["Battle! (Ice Rider Shadow Rider ​Calyrex) - Sword/Shield (Crown Tundra)"], type: "pokemon", region: "Galar",
    fileUrl: ["https://vgmsite.com/soundtracks/pokemon-sword-pokemon-shield-the-crown-tundra-super-music-collection/rviklzxkzi/16%20-%20Battle%21%20%28Ice%20Rider%20%20Shadow%20Rider%20Calyrex%29.mp3"], 
    imgUrl: ["https://docs.google.com/uc?export=download&id=1DfsZ8Kh7H3bBsri4M9k54k72dR-1gT2x", "https://docs.google.com/uc?export=download&id=16_coWZWLWghUJZgQFZj4d1xTH_QnOh5e"] },
    //94
];

export default songs;